version: '3.8'

services:
  postgres-db:
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: fiaplanches
    ports:
      - 5432:5432
    volumes:
      - postgres-db:/var/lib/postgresql/data
    networks:
      - fiap-lanchonete-network
        
#  fiap-lancher:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    ports:
#      - 8080:8080
#    volumes:
#      - fiap-lancher:/var/lib/fiaplancher/data
#    depends_on:
#      - postgres-db
#    networks:
#      - fiap-lanchonete-network

networks:
  fiap-lanchonete-network:
    driver: bridge

volumes:
  postgres-db:
    driver: local
#  fiap-lancher:
#    driver: local
